name: ci

# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  check-repo:
    runs-on: ubuntu-latest
    name: 'Check is this action in particular repo'
    if: ${{ github.event.repository.name == 'ts-openapi' }}
    steps:
      - name: 'Print action info'
        run: echo "event=${{ github.event_name }} event_ref=${{ github.event.ref }} repo=${{ github.event.repository.full_name }}"

  ci:
    runs-on: ubuntu-latest
    needs: check-repo
    strategy:
      matrix:
        node:
          - '14'
          - 'lts/*'
    name: Continuous integration (Node.js ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: 'Print latest 5 git logs'
        run: git log --branches --all --decorate --oneline -n 5
      - run: yarn install
      - run: yarn run build
      - run: yarn run test
      - run: ./test/gen-json.sh --install --silent --ci
      - run: npm pack --dryrun
